### PR TITLE
Do not crash if model misses any feature

### PR DESCRIPTION
**Pull request by toobaz**
This PR refactors a bit the extraction of features from ``statsmodels`` results, replaces missing features with ``None``, and prints ``None`` as an empty string.

This makes it at least possible to support non-OLS models by appropriately hiding e.g. the R2 with ``show_r2 = False``.

When no model has the R2, the line should be automatically hidden - will create a separate issue for that.

### CODE REVIEW

**Comment by spfraib** [comment]
Would you mind giving an example of how to use the option show_r2 = False? Much appreciated.

**Comment by toobaz** [comment]
> Would you mind giving an example of how to use the option show_r2 = False? Much appreciated.

In git master:

```python3
from statsmodels.datasets import grunfeld
from stargazer.stargazer import Stargazer
from statsmodels.api import Logit

data = grunfeld.load_pandas().data.set_index(['firm','year'])
mod = Logit(data.invest > 100, data[['value','capital']]).fit()

table = Stargazer([mod])
table.show_adj_r2 = table.show_r2 = False
table
```

**Comment by spfraib** [comment]
I am still getting an error when I run the code you just provided:

>>> table = Stargazer([mod])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/samuelfraiberger/opt/anaconda3/lib/python3.7/site-packages/stargazer/stargazer.py", line 31, in __init__
    self.extract_data()
  File "/Users/samuelfraiberger/opt/anaconda3/lib/python3.7/site-packages/stargazer/stargazer.py", line 96, in extract_data
    self.model_data.append(self.extract_model_data(m))
  File "/Users/samuelfraiberger/opt/anaconda3/lib/python3.7/site-packages/stargazer/stargazer.py", line 111, in extract_model_data
    data['r2'] = model.rsquared
  File "/Users/samuelfraiberger/opt/anaconda3/lib/python3.7/site-packages/statsmodels/base/wrapper.py", line 36, in __getattribute__
    obj = getattr(results, attr)
AttributeError: 'LogitResults' object has no attribute 'rsquared'

Could it be a issue with statsmodels version? I'm using
>>> statsmodels.__version__
'0.11.1'

**Comment by toobaz** [comment]
> Could it be a issue with statsmodels version? I'm using

Yes, as mentioned [here](https://github.com/mwburke/stargazer/pull/47#issuecomment-643835735) and [here](https://github.com/mwburke/stargazer/issues/52#issuecomment-643739164), this fix is still not included in any release

**Comment by toobaz** [comment]
> Could it be a issue with statsmodels version? I'm using

I think it's an issue with the ``stargazer`` version: as mentioned [above](https://github.com/mwburke/stargazer/pull/47#issuecomment-643835735) as well as [here](https://github.com/mwburke/stargazer/issues/52#issuecomment-643739164), this fix is still not included in a release.

**Comment by toobaz** [comment]
>  this fix is still not included in a release

(it is now)

**Pull request merged**
