### PR TITLE
Updated to dynamically create the number of columns in Latex code

### PR DESCRIPTION
**Pull request by brandonek15**
I tested the change locally with 2, 4, and 6 models and the latex code worked.

### CODE REVIEW

**Comment by toobaz** [comment]
This PR works (and it is badly needed - thanks @brandonek15 !), but let me suggest a slightly simpler and shorter version:

```python3
        content_columns = 'c' * len(self.num_models)
        header += '\\begin{tabular}{@{\\extracolsep{5pt}}l' + content_columns + '}\n'
```

**Comment by brandonek15** [comment]
That looks great! I'm happy to help and contribute to this project

**Comment by toobaz** [comment]
@brandonek15 if you like my proposed change, do you want to edit your PR accordingly, or do you want me to create a new one?

**Comment by brandonek15** [comment]
I updated my PR accordingly. I had to change from what you suggested to this.

`        content_columns = 'c' * self.num_models
        header += '\\begin{tabular}{@{\\extracolsep{5pt}}l' + content_columns + '}\n'`

I tested it locally and it works.

**Comment by toobaz** [comment]
> I updated my PR accordingly. I had to change from what you suggested to this.
> 
> `content_columns = 'c' * self.num_models`
> `header += '\\begin{tabular}{@{\\extracolsep{5pt}}l' + content_columns + '}\n'`

Sure, my code had a mistake.

It now looks great to me!

**Comment by brandonek15** [comment]
Great! Thanks for the suggestion to make it more concise

**Comment by toobaz** [comment]
Thanks @brandonek15 !

**Pull request merged**
